Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.synced_folder "..", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    yum install -y rpmdevtools ncurses-devel GeoIP-devel
    runuser -l vagrant -c rpmdev-setuptree
    runuser -l vagrant -c "ln -fs /vagrant/rpm/goaccess.spec /home/vagrant/rpmbuild/SPECS/"
    runuser -l vagrant -c "wget -q http://tar.goaccess.io/goaccess-1.0.2.tar.gz -O /home/vagrant/rpmbuild/SOURCES/goaccess-1.0.2.tar.gz"
    runuser -l vagrant -c "rpmbuild -ba /vagrant/rpm/goaccess.spec"
    mv /home/vagrant/rpmbuild/RPMS/x86_64/*.rpm /home/vagrant/rpmbuild/SRPMS/*.src.rpm /vagrant/rpm/
  SHELL
end
